################### Layout & Position ###################
legacy_layout=false
position=top-left
round_corners=10
background_alpha=0.55
background_color=1a1b26
font_size=22
text_color=e5e9f0
toggle_hud=Shift_R+F12
toggle_fps_limit=Shift_L+F1

################### Framerate ###################
fps
fps_limit=0
frame_timing=1
frametime_color=88c0d0

################### CPU ###################
cpu_stats
cpu_temp
cpu_power
cpu_text=CPU
cpu_color=a3be8c

################### GPU ###################
gpu_stats
gpu_temp
gpu_power
gpu_core_clock
gpu_mem_clock
gpu_text=GPU
gpu_color=bf616a

################### Memory ###################
ram
vram
ram_color=ebcb8b
vram_color=b48ead

################### Engine / System ###################
engine_version
vulkan_driver
gpu_name
wine
arch
resolution
